import type { Metadata } from "next"; 
import "./globals.css"; 
import { Dosis } from 'next/font/google'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const dosis = Dosis({
  subsets: ['latin'],
  display: 'swap',
  weight:'600',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={dosis.className} lang="en">
      <body >{children}</body>
    </html>
  );
}
