import type { Metadata } from "next"; 
import "./globals.css"; 
import { Dosis } from 'next/font/google'
import  Sidebar  from "../components/mainLayout/sidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const dosis = Dosis({
  subsets: ['latin'],
  display: 'swap',
  weight:'600',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={dosis.className} lang="en">
      <body > 
      <div className="grid min-h-screen w-full grid-cols-[280px_1fr]">
     <Sidebar></Sidebar>
      <div className="flex flex-col">
        <header className="flex h-14 items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40 lg:h-[60px]">
        
        </header>
        <main className="flex-1 gap-4 p-4 md:gap-8 md:p-6">
         {children}
          
        </main>
      </div>
    </div>


      </body>
    </html>
  );
}
