import type { Metadata } from "next";
import "./globals.css";
import { Dongle, Dosis, Gowun_Dodum } from "next/font/google";
import Sidebar from "../components/mainLayout/sidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dongle = Gowun_Dodum({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={dongle.className} lang="en">
      <body>
        <div className="grid min-h-screen w-full">
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
}
